from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views
from .views import brand_sku_view
# from .views import ask_gemini
urlpatterns = [
    path('',  LoginView.as_view(template_name='login.html'), name='login'),
    path('dash', views.dash, name = 'dash'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('select-brand', views.select_brand, name='select_brand'),
    # path('powerbi/', views.powerbi_dashboard, name='powerbi_dashboard'),
    path('brand-summary/', views.brand_summary, name='brand_summary'),
    path('googlenews',views.googlenews),
    path('consumersentiment/',views.consumersentiment),
    path('sms/',views.sms),
    path('get_chart_data',views.get_chart_data),
    path('get_chart_databuzz',views.get_chart_data_buzz),
    path('buzz',views.chart_view_buzz),
    path('apptracking1',views.valuetouser),
    path('apptracking2',views.scaleeng),   
    path('webtracking',views.webtracking),
    path('webtracking2',views.webtracking2),
    path('brand',views.brand),
    path('brandstrength',views.brandstrength,name='brandstrength'),
    path('cat',views.cat),
    path('store',views.store),
    
    path('brandsearchretailsov',views.brandsearch),
    path('retailsov',views.retailsov),
    path('estmarket',views.estmarket),
    path('appuser',views.appuser),
    path('appret',views.appret),
    path('appperf',views.appperf),
    path('brandstrengthoverviewtitle',views.brandstrengthoverviewtitle,name='brandstrengthoverviewtitle'),
    path('customerAffinityoverviewtitle',views.customerAffinityoverviewtitle),
    path('EngagementRates',views.EngagementRates),
    path('Brandperformanceoverview',views.Brandperformanceoverview),
    path('ntbmove',views.ntbmove),
    path('appsummary',views.appsummary),
    path('quality',views.quality),
    path('mind',views.mind),
    path('ntbchannel',views.ntbchannel),
    path('appsum',views.appsum),
    path('rank',views.rank),
    path('oneData',views.oneData),
    path('one',views.one),
    path('two',views.two),
    path('three',views.three),
    path('four',views.four,name='four'),
    path('five',views.five),
    path('six',views.six),
    path('seven',views.seven),
    path('eight',views.eight),
    path('nine',views.nine),
    path('ten',views.playstore),
    path('eleven',views.eleven),
    path('twelve',views.twelve),
    path('amc1',views.amc1),
    path('a',views.a),
    path('d',views.d),
    path('i',views.i),
    path('b',views.b),
    path('c',views.c),
    path('l',views.L),
    path('j',views.j),
    path('e',views.e),
    path('qcom',views.qcom),
    path('hivear',views.hivear),
    path('heliumdata',views.heliumData),
    path('heliumdata_a',views.heliumData_a),
    path('heliumdata_b',views.heliumData_b),
    path("ab",views.brand_sku_view),
    path("a1",views.a1),
    path("a2",views.a2),
    # path("a3",views.a3),
    path("a4",views.a4),
    # path("a5",views.a5),
    path("a6",views.a6),
    path('auth', views.flipkart_login_view),
    path('flipkart/exchange-token/', views.exchange_token_view, name='flipkart_exchange_token'),
    path('predict/', views.predict_score),



    ]
    
