# Generated by Django 5.1.4 on 2025-06-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MInD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlipkartToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_in', models.IntegerField()),
                ('refresh_expires_in', models.IntegerField()),
                ('token_type', models.CharField(max_length=20)),
                ('scope', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
